import sys

def Throw(error):
    print(error)
    sys.exit()